--USE TenentManagement;

--(V.0) Owners table --> Creation
--CREATE TABLE TBL_OWNER(
--ID INT PRIMARY KEY IDENTITY,
--FIRST_NAME VARCHAR(50),
--MIDDLE_NAME VARCHAR(50),
--LAST_NAME VARCHAR(50),
--AUTHID INT FOREIGN KEY REFERENCES TBL_AUTHENTICATION,
--PHONE_NUMBER NVARCHAR(20)
--);


-- (V.0.1) Added CREATED_AT for Owners Table
ALTER TABLE TBL_OWNER ADD CREATED_AT DATETIME DEFAULT GETDATE();