--USE TenentManagement;


--(V.0) Property table -> creation

--CREATE TABLE TBL_PROPERTY(
--ID INT PRIMARY KEY IDENTITY,
--NAME VARCHAR(100),
--ADDRESS VARCHAR(255),
--TYPE INT FOREIGN KEY REFERENCES TBL_PROPERTY_TYPES,
--DESCRIPTION VARCHAR(MAX),
--CREATEDAT DATETIME DEFAULT GETDATE(),
--USERID INT FOREIGN KEY REFERENCES TBL_OWNER,
--);


--ALTER TABLE TBL_PROPERTY ADD LATITUDE FLOAT;
--ALTER TABLE TBL_PROPERTY ADD LONGITUDE FLOAT;

--(V.1)

ALTER PROCEDURE SP_PROPERTY
@FLAG CHAR = NULL,
@ID INT = NULL,
@NAME VARCHAR(100) = NULL,
@ADDRESS VARCHAR(255) = NULL,
@LATITUDE FLOAT = NULL,
@LONGITUDE FLOAT = NULL,
@TYPE INT = NULL,
@DESCRIPTION VARCHAR(MAX) = NULL,
@CREATEDAT DATETIME = NULL,
@USERID INT = NULL
AS
BEGIN

	--for inserting new property in table
	IF @FLAG = 'I'
		BEGIN
			INSERT INTO TBL_PROPERTY
			(
			NAME
			,ADDRESS
			,LATITUDE
			,LONGITUDE
			,TYPE
			,DESCRIPTION
			,USERID
			)
			VALUES
			(
			@NAME
			,@ADDRESS
			,@LATITUDE
			,@LONGITUDE
			,@TYPE
			,@DESCRIPTION
			,@USERID
			)
		END

		--for getting single property detail
		IF @FLAG = 'S'
			BEGIN
				SELECT
				P.ID
				,P.NAME
				,P.ADDRESS
				,P.LATITUDE
				,P.LONGITUDE
				,PT.PROPERTY_TYPE TYPE
				,P.DESCRIPTION
				FROM TBL_PROPERTY P
				INNER JOIN TBL_PROPERTY_TYPES PT ON PT.ID = P.TYPE
				WHERE P.ID = @ID
			END

			--for getting all the property of the user
			IF @FLAG = 'R'
				BEGIN
					SELECT
					P.ID
					,P.NAME
					,P.ADDRESS
					,P.LATITUDE
					,P.LONGITUDE
					,PT.PROPERTY_TYPE TYPE
					FROM TBL_PROPERTY P
					INNER JOIN TBL_PROPERTY_TYPES PT ON PT.ID = P.TYPE
					WHERE P.USERID = @USERID
				END

			-- for updating the property detail
			IF @FLAG = 'U'
				BEGIN
					UPDATE TBL_PROPERTY
					SET
						NAME = ISNULL(@NAME, NAME),
						ADDRESS = ISNULL(@ADDRESS, ADDRESS),
						LATITUDE = ISNULL(@LATITUDE, LATITUDE),
						LONGITUDE = ISNULL(@LONGITUDE, LONGITUDE),
						TYPE = ISNULL(@TYPE, TYPE),
						DESCRIPTION = ISNULL(@DESCRIPTION, DESCRIPTION)
					WHERE ID = @ID;
				END

			--for deleting the property
			IF @FLAG = 'D'
				BEGIN
					DELETE FROM TBL_PROPERTY WHERE ID = @ID
				END
END
