--USE TenentManagement;

--Types of property --> creation

--CREATE TABLE TBL_PROPERTY_TYPES(
--ID INT PRIMARY KEY IDENTITY,
--PROPERTY_TYPE VARCHAR(50)
--);



-- Inserting land, home and commercial

INSERT INTO TBL_PROPERTY_TYPES VALUES ('LAND');
INSERT INTO TBL_PROPERTY_TYPES VALUES ('HOME');
INSERT INTO TBL_PROPERTY_TYPES VALUES ('COMMERCIAL');