--USE TenentManagement;


--(V.0) Property table -> creation

CREATE TABLE TBL_PROPERTY(
ID INT PRIMARY KEY IDENTITY,
NAME VARCHAR(100),
ADDRESS VARCHAR(255),
TYPE INT FOREIGN KEY REFERENCES TBL_PROPERTY_TYPES,
DESCRIPTION VARCHAR(MAX),
CREATEDAT DATETIME DEFAULT GETDATE(),
USERID INT FOREIGN KEY REFERENCES TBL_OWNER,
TOTAL_UNIT INT DEFAULT 1
);