--use TenentManagement;

--CREATE TABLE TBL_ROLES(
--ID INT PRIMARY KEY IDENTITY,
--NAME VARCHAR(25)
--);

--INSERT INTO TBL_ROLES VALUES ('ADMIN');
--INSERT INTO TBL_ROLES VALUES ('OWNER');
--INSERT INTO TBL_ROLES VALUES ('TENENT');

--SELECT * FROM TBL_ROLES
