
--USE TenentManagement
--(V.0) creating table for units
CREATE TABLE TBL_UNITS(
ID INT PRIMARY KEY IDENTITY,
NAME VARCHAR(100),
DESCRIPTION VARCHAR(255),
ISVACANT BIT DEFAULT 1,
RENTAMOUNT FLOAT,
RENTSTARTDATE DATETIME,
RENTENDDATE DATETIME,
RENTERID INT FOREIGN KEY REFERENCES TBL_USERS(ID),
PROPERTYID INT FOREIGN KEY REFERENCES TBL_PROPERTY(ID)
);
